{% set name = "transformers-interpret" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformers-interpret-{{ version }}.tar.gz
  sha256: 57595b8612071ce9666753376ca9e03524b9c14b1d0ae2b98bec21b194bd4b95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6
    - captum >=0.3.1
    - ipython >=7.31.1,<8.0.0
    - transformers >=3.0.0

test:
  imports:
    - transformers_interpret
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/transformers-interpret/
  summary: Model explainability that works seamlessly with 🤗 transformers. Explain your transformers model in just 2 lines of code.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Transformers Interpret is a model explainability tool designed to work exclusively with the 
    :hugs: transformers package.

    In line with the philosophy of the transformers package Tranformers Interpret allows any 
    transformers model to be explained in just two lines. It even supports visualizations in 
    both notebooks and as savable html files.

    PyPI: [https://pypi.org/project/transformers-interpret/](https://pypi.org/project/transformers-interpret/)

  doc_url: https://github.com/cdpierse/transformers-interpret#documentation
  dev_url: https://github.com/cdpierse/transformers-interpret

extra:
  recipe-maintainers:
    - sugatoray
